name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
   job1:
     runs-on: ubuntu-latest
     
     steps:
       - name: copy the code
         uses: actions/checkout@v3

       - name: recreate env file 
         run: |
          echo - "AWS_S3_ENDPOINT=${{secrets.AWS_S3_ENDPOINT}}" > .env
          echo - "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}" >> .env
          echo - "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> .env
          echo - "AWS_SESSION_TOKEN=${{secrets.AWS_SESSION_TOKEN}}" >> .env
       
       - name: build image docker    
         run: |
           docker build --tag yoriknyssen/mapds:v0.0.1 .
           
       - name: push image docker 
         run: |
          # Login in dockerhub
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          # Push image in dockerhub
          docker push yoriknyssen/mapds:v0.0.1
      
